"""empty message

Revision ID: b43b86399643
Revises: bb4d39547165
Create Date: 2026-09-14 23:54:11.637533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43b86399643'
down_revision = 'bb4d39547165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_role_assignment_person_id_person'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'person', ['person_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_role_assignment_person_id_person'), 'person', ['person_id'], ['id'])

    # ### end Alembic commands ###
