"""make role_assignment.person_id non-nullable

Revision ID: bb4d39547165
Revises: 6c0bf85bcfdf
Create Date: 2026-09-14 23:50:05.353135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4d39547165'
down_revision = '6c0bf85bcfdf'
branch_labels = None
depends_on = None


def upgrade():
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"
    }
    with op.batch_alter_table(
        'role_assignment',
        schema=None,
        naming_convention=naming_convention,
        recreate='always'
    ) as batch_op:
        batch_op.alter_column(
            'person_id',
            existing_type=sa.Integer(),
            nullable=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'person', ['person_id'], ['id'])
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
